spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://172.16.57.87:5432/booking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 172.16.57.87
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        bookingCreated-out-0:
          destination: BOOKING_CREATED
      default-binder: rabbit

server:
  port: 8083

eureka:
  client:
    service-url.defaultZone: http://172.16.57.87:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}